###################################################################################################################
# The deployment of the application namespace
###################################################################################################################

apiVersion: v1
kind: Namespace
metadata:
  name: app2
